### ISSUE TITLE
Merge gh-pages and master branches?

### ISSUE THREAD

**Issue by dmitrizagidulin** [veres-one/docs.veres.one#7]
I notice there's both a `gh-pages` and a `master` here, slightly out of sync. GitHub now lets you publish `master` directly on github.io -- might it make sense to combine these two?

**Comment by msporny** [comment]
gh-pages is autogenerated from master when you run the `mkdocs publish` command. In other words, you do all the dev stuff in markdown on the `master` branch. Then you preview using `mkdocs serve`... then once you're happy with it,  you do `mkdocs publish`, which compiles a single page site using mkdocs and commits that to gh-pages.

**Comment by dmitrizagidulin** [comment]
Ah, no prob. I was just concerned about the '60 commits ahead / 137 commits behind' part. Will close the issue :)
